/*
 * This file was generated by the Gradle 'init' task.
 */

allprojects {
    repositories {
        // Use the plugin portal to apply community plugins in convention plugins.
        maven {
            url = uri("https://nexus.mcmcnet.cn/repository/maven-public/")
        }
    }
}
