/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    val springBootVersion = "2.5.2"

    application
    id("org.springframework.boot") version springBootVersion
}
apply(plugin = "io.spring.dependency-management")

tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    mainClass.set("cn.wunhwan.authorization.SecurityApplication")
}

dependencies {
    val jwtVersion = "0.11.2"

    /* spring-boot */
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-actuator")

    /* jwt */
    implementation("io.jsonwebtoken:jjwt-api:${jwtVersion}")
    implementation("io.jsonwebtoken:jjwt-impl:${jwtVersion}")
    implementation("io.jsonwebtoken:jjwt-jackson:${jwtVersion}")

    /* database */
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("com.h2database:h2")

    /* util */
    implementation("org.apache.commons:commons-lang3")
}


configure<io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension> {
    val springCloudVersion = "2020.0.3"

    imports(delegateClosureOf<io.spring.gradle.dependencymanagement.dsl.ImportsHandler> {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
    })
}
